export const meals = [
  {
    name: "Wrap",
    difficulty: "easy",
    time: "fast",
    tags: ["main", "healthy", "empty-the-fridge"],
    description: "Tortilla + anything that is in the fridge.",
  },
  {
    name: "Chocolate chip cookies",
    difficulty: "easy",
    time: "slow",
    tags: ["dessert", "snack", "showstopper", "vegeterian"],
    description: "Indulgent chocolate chip cookies.",
    url: "https://www.youtube.com/watch?v=rEdl2Uetpvo",
  },
  {
    name: "Tiramisu Semifredo",
    difficulty: "medium",
    time: "very-slow",
    tags: ["dessert", "showstopper", "vegeterian"],
    description: "Extra rich and creamy dessert.",
    url: "https://www.youtube.com/watch?v=87V4nizNJiE",
  },
  {
    name: "Frirata",
    difficulty: "easy",
    time: "fast",
    tags: ["main", "empty-the-fridge", "breakfast", "vegeterian"],
    description:
      "Omelette + anything in fridge. Good for any amount of people.",
  },
  {
    name: "German pancake",
    difficulty: "easy",
    time: "medium",
    tags: [
      "main",
      "breakfast",
      "pancake",
      "showstopper",
      "vegeterian",
    ],
    description: "Big puffy pancake with any delicious toppings you want",
    url: "https://www.youtube.com/watch?v=6gpoV6zCHkQ",
  },
  {
    name: "French omelette",
    difficulty: "insane",
    time: "fast",
    tags: ["main", "breakfast", "vegeterian"],
    description: "3 eggs rolled up into delicious custardy roll.",
    url: "https://www.youtube.com/watch?v=A-pqjLgFCqw",
  },
  {
    name: "Pasta",
    difficulty: "easy",
    time: "fast",
    tags: ["main", "showstopper"],
    description: "Mince + sauce + pasta. Yum.",
  },
  {
    name: "Burger",
    difficulty: "easy",
    time: "fast",
    tags: ["main", "snack"],
    description: "Meaaaaaaat!",
  },
  {
    name: "Fries",
    difficulty: "easy",
    time: "fast",
    tags: ["side", "snack", "frozen", "vegan"],
    description: "Tesco fries cooked from frozen and ready in 20 min.",
    url: "https://www.tesco.com/groceries/en-GB/shop/frozen-food/chips-potatoes-and-sides/chips-and-french-fries/frozen-chips-french-fries",
  },
  {
    name: "Tomato mozarella salad",
    difficulty: "easy",
    time: "slow",
    tags: ["starter", "showstopper", "vegeterian"],
    description:
      "Beautify cut tomato slices and basel with mozarella or burrata centerpiece.",
  },
  {
    name: "Youghurt + oats + fruits",
    difficulty: "easy",
    time: "super-fast",
    tags: ["main", "super-fast", "breakfast", "healthy", "vegeterian"],
    description: "Very fast and healthy start of a day.",
  },
  {
    name: "Tomato salad",
    difficulty: "easy",
    time: "fast",
    tags: ["salad", "healthy", "vegan"],
    description: "All the tomatoe types, red onion and herbs mixed.",
  },
  {
    name: "Beigin duck",
    difficulty: "medium",
    time: "slow",
    tags: ["main", "healthy", "frozen"],
    description:
      "Mini wraps with delicious sauce and cucumbers and spring onion strips.",
  },
  {
    name: "Ceaser salad",
    difficulty: "easy",
    time: "fast",
    tags: ["salad", "fast"],
    description: "Same as burger but different textures.",
  },
  {
    name: "Roast chicken spatchcock",
    difficulty: "medium",
    time: "very-slow",
    tags: ["main", "showstopper", "healthy"],
    description: "Classic roast chicken",
    url: "https://www.youtube.com/watch?v=pod4x5NJoYI",
  },
  {
    name: "Rice",
    difficulty: "easy",
    time: "fast",
    tags: ["side", "healthy", "vegan"],
    description: "Steamed rice, don't forget the right proportions.",
    url: "https://www.youtube.com/watch?v=Jf75I9LKhvg",
  },
  {
    name: "Potato mash",
    difficulty: "easy",
    time: "fast",
    tags: ["side", "healthy", "vegan"],
    description: "Simple potato",
  },
  {
    name: "Sweet potato mash",
    difficulty: "easy",
    time: "fast",
    tags: ["side", "healthy", "vegan"],
    description: "Better potato",
  },
  {
    name: "Egg noodle",
    difficulty: "easy",
    time: "super-fast",
    tags: ["side", "super-fast", "healthy", "vegeterian"],
    description: "Better version of instant noodle",
  },
  {
    name: "Kale crips",
    difficulty: "easy",
    time: "fast",
    tags: ["snack", "healthy", "vegan", "vegeterian"],
    description: "Delicious helthy crisps",
  },
  {
    name: "Knafeh",
    difficulty: "medium",
    time: "slow",
    tags: ["dessert", "vegeterian", "showstopper"],
    description: "Delicious cheesy dessert with honey",
  },
  {
    name: "Ratatouille",
    difficulty: "easy",
    time: "slow",
    tags: ["main", "vegan", "vegeterian"],
    description: "Baked bunch of veggies",
  },
  {
    name: "Pancake",
    difficulty: "easy",
    time: "slow",
    tags: ["main", "vegeterian"],
    description: "A brown thin, round cake",
  },
  {
    name: "Dauphinoise potatoes",
    difficulty: "medium",
    time: "side",
    tags: ["main", "side", "vegeterian"],
    description: "Very cheesy potatoes.",
  },
  {
    name: "Grilled Halloumi cheese",
    difficulty: "easy",
    time: "fast",
    tags: ["side", "vegeterian"],
    description: "Mashallah",
  },
  {
    name: "Cheese platter",
    difficulty: "easy",
    time: "fast",
    tags: ["side", "vegeterian"],
    description:
      "Create a tasting session of different cheeses from hard to soft ones.",
  },
  {
    name: "Chocolate cake",
    difficulty: "???",
    time: "very-slow",
    tags: ["dessert"],
    description: "Mashallah",
  },
  {
    name: "Coleslaw",
    difficulty: "easy",
    time: "fast",
    tags: ["salad", "vegeterian", "healthy"],
    description: "Shredded cabbage and carrots with creamy dressing.",
  },
  {
    name: "Water",
    difficulty: "easy",
    time: "super-fast",
    tags: ["drink", "super-fast"],
    description: "The best drink ever",
  },
  {
    name: "Mojito",
    difficulty: "easy",
    time: "super-fast",
    tags: ["drink", "super-fast", "cocktail", "alcoholic"],
    description: "Lime, mint, sugar, soda and rum over ice.",
  },
  {
    name: "Croissant (frozen)",
    difficulty: "easy",
    time: "slow",
    tags: ["snack", "breakfast", "frozen"],
    description: "Bake-from-frozen croissants until puffed and golden.",
  },
  {
    name: "Sunrise mocktail",
    difficulty: "easy",
    time: "super-fast",
    tags: ["drink", "super-fast", "mocktail", "non-alcoholic"],
    description: "Layered orange juice and grenadine over ice.",
  },
  {
    name: "Lemonade",
    difficulty: "easy",
    time: "super-fast",
    tags: ["drink", "super-fast", "mocktail", "non-alcoholic", "healthy"],
    description: "Fresh lemon juice, water and sugar to taste.",
  },
  {
    name: "Steak",
    difficulty: "medium",
    time: "fast",
    tags: ["main", "showstopper"],
    description: "Pan-seared steak with butter baste and rest.",
  },
  {
    name: "Ayran",
    difficulty: "easy",
    time: "super-fast",
    tags: ["drink", "super-fast", "non-alcoholic", "vegeterian", "healthy"],
    description: "Yoghurt blended with cold water and a pinch of salt.",
  },
  {
    name: "Okra",
    difficulty: "medium",
    time: "slow",
    tags: ["side", "healthy", "vegan", "vegeterian"],
    description: "Stewed or sautéed okra with aromatics.",
  },
  {
    name: "Cordial",
    difficulty: "easy",
    time: "very-slow",
    tags: ["drink", "non-alcoholic"],
    description: "Homemade fruit syrup concentrate for mixing.",
  },
  {
    name: "Crepes",
    difficulty: "easy",
    time: "slow",
    tags: ["dessert", "breakfast", "vegeterian"],
    description: "Thin pancakes with sweet or savoury fillings.",
  },
  {
    name: "Lasagna",
    difficulty: "medium",
    time: "very-slow",
    tags: ["main", "showstopper"],
    description: "Layered pasta bake with sauce and cheese.",
  },
  {
    name: "Giga platter (chicken, potatoes, veggies)",
    difficulty: "medium",
    time: "slow",
    tags: ["main", "showstopper", "healthy"],
    description: "Big roasting tray with chicken, potatoes and mixed veg.",
  },
  {
    name: "Dumplings",
    difficulty: "medium",
    time: "slow",
    tags: ["main"],
    description: "Boiled or pan-fried dumplings with dipping sauce.",
  },
  {
    name: "Pain au chocolat",
    difficulty: "easy",
    time: "slow",
    tags: ["snack", "breakfast"],
    description: "Flaky pastry with a rich chocolate bar inside.",
  },
  {
    name: "Schnitzel",
    difficulty: "medium",
    time: "fast",
    tags: ["main", "showstopper"],
    description: "Breaded, shallow-fried cutlet (chicken, pork or veal).",
  },
  {
    name: "Pea soup",
    difficulty: "easy",
    time: "side",
    tags: ["main", "side", "healthy", "vegeterian"],
    description: "Smooth or chunky pea soup with herbs.",
  },
  {
    name: "Garlic bread",
    difficulty: "easy",
    time: "fast",
    tags: ["main", "healthy", "vegeterian"],
    description: "Delicious side for soup or indian kitchen.",
  },
  {
    name: "Stuffed pepper or other veg",
    difficulty: "???",
    time: "???",
    tags: ["main", "side"],
    description: "A lot of mince disguised as a vegetable",
  },
  {
    name: "Beef stir fry",
    difficulty: "easy",
    time: "fast",
    tags: ["main", "fast"],
    description: "Pan + beef + spices",
  },
  {
    name: "Crispy potato cubes",
    difficulty: "medium",
    time: "slow",
    tags: ["side"],
    description: "crunchy (hopefully)",
  },
  {
    name: "Crispy duck salad",
    difficulty: "???",
    time: "???",
    tags: ["main", "side"],
    description: "Inspired by the Ivy restaurant.",
  },
];
